### PR TITLE
Improved UI of the website

### LINKED ISSUE #3: [Enhancement]: The UI needs a changeover
I created this app from a prebuilt TailwindCSS template I picked up from the internet. The UI needs improvements and good looks.

### PR DESCRIPTION
**Pull request by Nikhil7174**
## Description

Improved UI of the website

## Issue Resolved

Fixes #3 

## Screenshots 
Screenshot (255)
Screenshot (254)

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/MSB-s-Projects/Generate-QR-code/blob/main/docs/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by Manobal-Singh-Bagady — APPROVED** [review]
Good Work @Nikhil7174, The UI Looks Amazing.

**Review by Manobal-Singh-Bagady — CHANGES_REQUESTED** [review]
Just a little thing can you also add a footer to the UI similar to this:

image

**Comment by Nikhil7174** [comment]
@Manobal-Singh-Bagady The footer is ready can you please merge this pr so that I can create a new one for the footer issue

**Comment by Manobal-Singh-Bagady** [comment]
> @Manobal-Singh-Bagady The footer is ready can you please merge this pr so that I can create a new one for the footer issue

Alright

**Review by Manobal-Singh-Bagady — APPROVED** [review]
Everything looks good. Merging the PR

**Pull request merged**
