### PR TITLE
Issue No #5

### LINKED ISSUE #5: [Feature Request]: Need create QR code of links.
Right now, the app only encodes plain text to QR codes. We need functionality so users can also create QR codes out of links.

The UI will also be needed to update:
 
we need something similar to this
image

there are two sections and the user can choose if they want to encode plain text or urls.

### PR DESCRIPTION
**Pull request by ugpec79**
## Description

For Text and URL I have made a common path so that it is choice of user to put text or URL once at a time

## Issue Resolved

Fixes #5 

## Checklist

Please make sure to review the following before submitting your PR: 

- [ x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [ x] I have read the code of conduct.
- [ x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady pls review the pr and suggest the change if needed in the concept

**Review by Manobal-Singh-Bagady — CHANGES_REQUESTED** [review]
Yes, @ugpec79, you can encode links and plain text from this app. But we need to make changes in the front end so that there are two different tabs, as shown in #5, So you'll need to implement that.

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady  since its a frontend issue I am unassigning myself thank u for your review

**Comment by Manobal-Singh-Bagady** [comment]
> @Manobal-Singh-Bagady since its a frontend issue I am unassigning myself thank u for your review

Alright, @ugpec79, sorry for the unclear instructions, and thanks for showing interest in this project. You can work on the other issue, which is purely based on backend #4

**Pull request closed without merging**
