### PR TITLE
Issue No. #4

### LINKED ISSUE #4: [Feature Request]: Need the functionality so that user can upload their photos and they can be converted into a QR code.
I have seen QR codes that can contain pictures. When someone scans that QR code, a photo shows up. We need to add that function to the app.

### PR DESCRIPTION
**Pull request by ugpec79**
## Description

I have added Image upload functionality basically on just upload of image the form is submitted with clicking button as of now 
and I have merged index.js in app.js for working condition and commented some error code in order for the code to work and its working 
To test it in backend replace your website url with localhost:3000 and setup mongoDB
Improvement can be done in:
UI 
Backend Restructuring (if necessary) else its working
## Issue Resolved
Fixes #4 

## Screenshots 

Provide some screenshots of the changes made (if applicable).
d
dcs
image
dsc
dsdc

in one image its website name since it was added by me in url but i changed it to localhost 3000 as u can see in next image

## Checklist

Please make sure to review the following before submitting your PR: 

- [x ] I have read the [contribution guidelines](https://github.com/MSB-s-Projects/Generate-QR-code/blob/main/docs/CONTRIBUTING.md).
- [x ] I have read the code of conduct.
- [ x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady pls review pr and request any change

**Comment by ugpec79** [comment]
Ok 👌

**Review by Manobal-Singh-Bagady — CHANGES_REQUESTED** [review]
Alright, @ugpec79, I have reviewed your changes. GW. 
But here's a request. As the image functionality still needs some work I want to merge your PR into a different branch I have created the branch [image-functionality](https://github.com/MSB-s-Projects/Generate-QR-code/tree/image-fuctionality) please make another PR into that branch. I will definitely merge it.

**Comment by ugpec79** [comment]
ok

**Pull request closed without merging**
