### PR TITLE
added correct link to access the web application

### PR DESCRIPTION
**Pull request by dhruv-porwal**
## Description

added correct link to access the application online

## Issue Resolved

Link to the issue that is resolved by this pull request goes here e.g. Fixes #10.

## Screenshots 

Provide some screenshots of the changes made (if applicable).

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/MSB-s-Projects/Generate-QR-code/blob/main/docs/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by Manobal-Singh-Bagady — APPROVED** [review]
Good eye there @dhruv-porwal, It totally slipped my mind 😅

**Review by Manobal-Singh-Bagady — CHANGES_REQUESTED** [review]
- [ ] Commnet on #29 so that i can assign the issue to you.
- [ ] Please remove the default template from the pull request and write an appropriate description.

**Comment by dhruv-porwal** [comment]
> 

OK

**Comment by dhruv-porwal** [comment]
Sir made a PR kindly merge it.

**Comment by dhruv-porwal** [comment]
> done



> done

**Review by Manobal-Singh-Bagady — APPROVED** [review]
Alright everything looks good, merging the PR.

**Pull request merged**
